INSERT INTO HOTEL (ID, NAME, ADDRESS, MODIFIED) VALUES ('NYC1', 'Grand Central Hotel', '101 5th Ave, New York, NY 10001', false);
INSERT INTO HOTEL (ID, NAME, ADDRESS, MODIFIED) VALUES ('NYC2', 'Pen Station Hotel', '101 7th Ave, New York, NY 10002', false);

INSERT INTO ROOM (ID, HOTEL_ID, NAME, ROOM_NUMBER, BED_TYPE, MODIFIED) VALUES (1001, 'NYC1', 'Royal Suite', 'g1', 'K', false);
INSERT INTO ROOM (ID, HOTEL_ID, NAME, ROOM_NUMBER, BED_TYPE, MODIFIED) VALUES (1002, 'NYC1', 'Budget Suite', 'f1', 'Q', false);
INSERT INTO ROOM (ID, HOTEL_ID, NAME, ROOM_NUMBER, BED_TYPE, MODIFIED) VALUES (2001, 'NYC2', 'Comfort Room', 'k1', 'T', false);
INSERT INTO ROOM (ID, HOTEL_ID, NAME, ROOM_NUMBER, BED_TYPE, MODIFIED) VALUES (2002, 'NYC2', 'Royal Suite', 'g1', 'Q', false);
