CREATE TABLE ROOM(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  HOTEL_ID VARCHAR(16),
  NAME VARCHAR(128) NOT NULL,
  ROOM_NUMBER CHAR(2) NOT NULL,
  BED_TYPE CHAR(2) NOT NULL,
  MODIFIED BOOL
);

CREATE TABLE HOTEL(
  ID VARCHAR(16) PRIMARY KEY,
  NAME VARCHAR(256) NOT NULL,
  ADDRESS VARCHAR(256) NOT NULL,
  MODIFIED BOOL
);

CREATE TABLE BOOKING(
  ID VARCHAR(16) PRIMARY KEY,
  NAME VARCHAR(256) NOT NULL,
  HOTEL_ID VARCHAR(16) NOT NULL,
  ROOM_ID BIGINT NOT NULL,
  CHECKIN_DATE DATE,
  CHECKOUT_DATE DATE,
  MODIFIED BOOL
);


